#
# Package 'target/02-jarkarta-microprofile.war' in an applicaiton server.
#
# Please use JDK 11 in your container
#
# To ensure the app is running you can use curl (the exact path might be different, depending on your application server)
# 'http://localhost:8080/02-jarkarta-microprofile/resources/ping'
