#
# Try to package the resulting jar '01-simple-app-1.0-SNAPSHOT.jar' and expose the correct port.
# Use an appropriate base image with JDK 17.
#
# You can verify that the app is running by invoking 'curl -i localhost:8080/hello'
#
# As a bonus: Add a Docker Health-Check to ensure the server is running:
# https://docs.docker.com/engine/reference/builder/#healthcheck
